### ISSUE TITLE
Inconsistency in template

### ISSUE THREAD

**Issue by pzygielo** [bshannon/spec-template#2]
See https://github.com/eclipse-ee4j/jsp-api/pull/106#discussion_r303234102

**Comment by pzygielo** [comment]
And
> [ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc (asciidoc-to-html) on project jdsol-spec: The plugin org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1 requires Maven version 3.0.5 -> [Help 1]

vs https://github.com/bshannon/spec-template/blob/287ffb66312a615cfc147658b939af8ab4ee0972/README.md#L12

**Comment by pzygielo** [comment]
Addressed in #3 and #4.

**Comment by pzygielo** [comment]
@bshannon Hi Bill,
Regarding JDK version - could you clarify which way you'd like it to be
1. as in readme - allow JDK >= 1.8
1. as implemented in rule - JDK fixed to 1.8?

**Comment by bshannon** [comment]
Since we're working on Jakarta EE 8 and everything needs to work with Java SE 8,
I only expected it to work with JDK 1.8.  If it happens to work with newer versions of
the JDK, that's great, but I haven't had time to check it.

**Comment by pzygielo** [comment]
Thank you for your reply. 
Then I think, the current state of #4, that fixes JDK version to 1.8 in readme and adjusts message for rule violation in other cases, reflects that.
I updated PR's title.

**Comment by pzygielo** [comment]
Closed by #4, #3.
